### ISSUE TITLE
Ошибка в создании сладости

### ISSUE THREAD

**Issue by nevermorest** [Nervniy1Enot/Konfetki#2]
В момент создания сладости тип данных для этой функции имеет тип boolean значения которого могут принимать только 0 или 1
В вашем случае допущена ошибка, поскольку переменная принимает значение "нет", что значит 0
Скорее всего вы не учли тип данных для типа boolean, стоит изменить значение с "нет" на 0

**Comment by Nervniy1Enot** [comment]
commit [aaf4104](https://github.com/Nervniy1Enot/Konfetki/commit/aaf410419b666f38791b04614984e647f7d1cfb9)
